spring:
  application:
    name: sbweek3

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3308/ebrainsoft_study
    username: ebsoft
    password: ebsoft

  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp

server:
  servlet:
    jsp:
      init-parameters:
        development: true

mybatis:
  # Mapper XML 파일의 위치
  mapper-locations: classpath:mappers/*.xml

  # MyBatis 설정
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

# 로깅 설정
logging:
  level:
    com.job.dashboard: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

image:
  upload:
    dir: C:\STUDY\workspace\img
